name: deploy
on:
  push:
    branches: [main]
    
    
job:
  run-on: ubuntu-latest
  
  - name: code checkout
     uses: action/checkout@v4
     
  - name: copy file to server
    uses: appleboy/scp-action@v0.1.7
    with:
      source: "."
      target: "var/www/html"
    
